M48
; DRILL file {KiCad 9.0.7} date 2026-02-05T16:57:56-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-05T16:57:56-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X3.9807Y-2.8236
X4.2083Y-2.8236
T2
X4.0945Y-2.8888
M30
